default_provider: lms_deepseek

providers:
  openai:
    base_url: "https://api.openai.com/v1"
    model: "gpt-4.1-mini"
    api_key_env: "OPENAI_API_KEY_GIT"
    protocol: "responses"

  grok:
    base_url: "https://api.x.ai/v1"
    model: "grok-3-mini"
    api_key_env: "XAI_API_KEY"
    protocol: "responses"

  lms_gpt:
    base_url: "http://jmr-studio.local:1234/v1"
    model: "openai/gpt-oss-20b"
    api_key_env: "LMSTUDIO_API_KEY"
    protocol: "chat"

  lms_deepseek:
    base_url: "http://jmr-studio.local:1234/v1"
    model: "deepseek-coder-v2-lite-instruct-mlx"
    api_key_env: "LMSTUDIO_API_KEY"
    protocol: "chat"
